---
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 1
  rounds:
  - label: composer
    txNumber:
    - 300
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 300
    arguments:
      testAssets: 0
    callback: benchmark/composer/composer-samples/composer.js
  - label: composer
    txNumber:
    - 100
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1000
    arguments:
      testAssets: 0
    callback: benchmark/composer/composer-samples/composer.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
